quiet: False
keeptree: False
with-expecter: true
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
outpkg: mocks
dir: mocks
packages:
    github.com/thejasn/go-sqs/consumer:
        config:
        interfaces:
            SQSClientInterface:
            SQSService:

